version: "3.9"
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/config
    networks:
      - snipe-it

  trudesk:
    image: polonel/trudesk:1
    restart: always
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
    volumes:
      - ./data/trudesk/uploads:/usr/src/trudesk/public/uploads
      - ./data/trudesk/backups:/usr/src/trudesk/backups
    networks:
      - snipe-it

  mongo:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - ./data/mongo/lib:/var/lib/mongo
      - ./data/mongo/data:/data/db:rw
    networks:
      - snipe-it

  elasticsearch:
    image: elasticsearch:8.0.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - snipe-it

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://$SNIPE_DOMAIN
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_LOCALE=en
    volumes:
      - ./data/snipe-it:/config
    restart: unless-stopped
    networks:
      - snipe-it

  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:alpine
    restart: always
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - /var/log:/var/log
    environment:
      - SNIPE_DOMAIN=${SNIPE_DOMAIN}
      - TRUDESK_DOMAIN=${TRUDESK_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - snipe-it

networks:
  snipe-it:
    driver: bridge
    name: snipe-it
