version: "3.9"
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/config
    networks:
      - snipe-it

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - snipe-it

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    restart: always
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$API_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: "postgres"
      SECRET: ${PEPPERMINT_SECRET}
      API_URL: ${PEPPERMINT_API_DOMAIN}
    networks:
      - snipe-it

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://$SNIPE_DOMAIN
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_LOCALE=en
    volumes:
      - ./data/snipe-it:/config
    restart: unless-stopped
    networks:
      - snipe-it

  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:alpine
    restart: always
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - /var/log:/var/log
    environment:
      - SNIPE_DOMAIN=${SNIPE_DOMAIN}
      - PEPPERMINT_DOMAIN=${PEPPERMINT_DOMAIN}
      - PEPPERMINT_API_DOMAIN=${PEPPERMINT_API_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - snipe-it

networks:
  snipe-it:
    driver: bridge
    name: snipe-it
